services:
  medplum-app:
    image: ghcr.io/${{ github.repository }}:latest
    environment:
      - MEDPLUM_BASE_URL
      - MEDPLUM_CLIENT_ID
      - GOOGLE_CLIENT_ID
      - RECAPTCHA_SITE_KEY
      - MEDPLUM_REGISTER_ENABLED
      - MEDPLUM_AWS_TEXTRACT_ENABLED
    env_file:
      - .env
    restart: always
    ports:
      - '8104:3000'
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000']
      interval: 10s
      timeout: 5s
      retries: 5